// Copyright (c) 2019 Chris Ohk

// We are making my contributions/submissions to this project solely in our
// personal capacity and are not conveying any rights to any intellectual
// property of any third parties.

#ifndef CONQUER_THE_SPIRE_CARD_ID_HPP
#define CONQUER_THE_SPIRE_CARD_ID_HPP

namespace ConquerTheSpire
{
//! Every card the registry can build. Cards refer to each other by id, which
//! is what lets a card copy, upgrade or create another one.
enum class CardId
{
    INVALID = 0,

    // Ironclad - basic
    STRIKE_RED,
    DEFEND_RED,
    BASH,

    // Ironclad - common
    ANGER,
    ARMAMENTS,
    BODY_SLAM,
    CLASH,
    CLEAVE,
    CLOTHESLINE,
    FLEX,
    HAVOC,
    HEADBUTT,
    HEAVY_BLADE,
    IRON_WAVE,
    PERFECTED_STRIKE,
    POMMEL_STRIKE,
    SHRUG_IT_OFF,
    SWORD_BOOMERANG,
    THUNDERCLAP,
    TRUE_GRIT,
    TWIN_STRIKE,
    WARCRY,
    WILD_STRIKE,

    // Ironclad - uncommon
    BATTLE_TRANCE,
    BLOOD_FOR_BLOOD,
    BLOODLETTING,
    BURNING_PACT,
    CARNAGE,
    COMBUST,
    DARK_EMBRACE,
    DISARM,
    DROPKICK,
    DUAL_WIELD,
    ENTRENCH,
    EVOLVE,
    FEEL_NO_PAIN,
    FIRE_BREATHING,
    FLAME_BARRIER,
    GHOSTLY_ARMOR,
    HEMOKINESIS,
    INFERNAL_BLADE,
    INFLAME,
    INTIMIDATE,
    METALLICIZE,
    POWER_THROUGH,
    PUMMEL,
    RAGE,
    RAMPAGE,
    RECKLESS_CHARGE,
    RUPTURE,
    SEARING_BLOW,
    SECOND_WIND,
    SEEING_RED,
    SENTINEL,
    SEVER_SOUL,
    SHOCKWAVE,
    SPOT_WEAKNESS,
    UPPERCUT,
    WHIRLWIND,

    // Ironclad - rare
    BARRICADE,
    BERSERK,
    BLUDGEON,
    BRUTALITY,
    CORRUPTION,
    DEMON_FORM,
    DOUBLE_TAP,
    EXHUME,
    FEED,
    FIEND_FIRE,
    IMMOLATE,
    IMPERVIOUS,
    JUGGERNAUT,
    LIMIT_BREAK,
    OFFERING,
    REAPER,

    // Silent - basic
    STRIKE_GREEN,
    DEFEND_GREEN,
    NEUTRALIZE,
    SURVIVOR,

    // Silent - common
    ACROBATICS,
    BACKFLIP,
    BANE,
    BLADE_DANCE,
    CLOAK_AND_DAGGER,
    DAGGER_SPRAY,
    DAGGER_THROW,
    DEADLY_POISON,
    DEFLECT,
    DODGE_AND_ROLL,
    FLYING_KNEE,
    OUTMANEUVER,
    PIERCING_WAIL,
    POISONED_STAB,
    PREPARED,
    QUICK_SLASH,
    SLICE,
    SNEAKY_STRIKE,
    SUCKER_PUNCH,

    // Silent - uncommon
    ACCURACY,
    ALL_OUT_ATTACK,
    BACKSTAB,
    BLUR,
    BOUNCING_FLASK,
    CALCULATED_GAMBLE,
    CALTROPS,
    CATALYST,
    CHOKE,
    CONCENTRATE,
    CRIPPLING_CLOUD,
    DASH,
    DISTRACTION,
    ENDLESS_AGONY,
    ESCAPE_PLAN,
    EVISCERATE,
    EXPERTISE,
    FINISHER,
    FLECHETTES,
    FOOTWORK,
    HEEL_HOOK,
    INFINITE_BLADES,
    LEG_SWEEP,
    MASTERFUL_STAB,
    NOXIOUS_FUMES,
    PREDATOR,
    REFLEX,
    RIDDLE_WITH_HOLES,
    SETUP,
    SKEWER,
    TACTICIAN,
    TERROR,
    WELL_LAID_PLANS,

    // Silent - rare
    A_THOUSAND_CUTS,
    ADRENALINE,
    AFTER_IMAGE,
    BULLET_TIME,
    BURST,
    CORPSE_EXPLOSION,
    DIE_DIE_DIE,
    DOPPELGANGER,
    ENVENOM,
    GLASS_KNIFE,
    GRAND_FINALE,
    MALAISE,
    NIGHTMARE,
    PHANTASMAL_KILLER,
    ALCHEMIZE,
    STORM_OF_STEEL,
    TOOLS_OF_THE_TRADE,
    UNLOAD,
    WRAITH_FORM,

    // Silent - made by other cards
    SHIV,

    // Defect - basic
    STRIKE_BLUE,
    DEFEND_BLUE,
    ZAP,
    DUALCAST,

    // Defect - common
    BALL_LIGHTNING,
    BARRAGE,
    BEAM_CELL,
    CHARGE_BATTERY,
    CLAW,
    COLD_SNAP,
    COMPILE_DRIVER,
    COOLHEADED,
    GO_FOR_THE_EYES,
    HOLOGRAM,
    LEAP,
    REBOUND,
    RECURSION,
    STACK,
    STEAM_BARRIER,
    STREAMLINE,
    SWEEPING_BEAM,
    TURBO,

    // Defect - uncommon
    AGGREGATE,
    AUTO_SHIELDS,
    BLIZZARD,
    BOOT_SEQUENCE,
    BULLSEYE,
    CAPACITOR,
    CHAOS,
    CHILL,
    CONSUME,
    DARKNESS,
    DEFRAGMENT,
    DOOM_AND_GLOOM,
    DOUBLE_ENERGY,
    EQUILIBRIUM,
    FORCE_FIELD,
    FTL,
    FUSION,
    GENETIC_ALGORITHM,
    GLACIER,
    HEATSINKS,
    HELLO_WORLD,
    LOOP,
    MELTER,
    OVERCLOCK,
    RECYCLE,
    REINFORCED_BODY,
    REPROGRAM,
    RIP_AND_TEAR,
    SCRAPE,
    SELF_REPAIR,
    SKIM,
    STATIC_DISCHARGE,
    STORM,
    SUNDER,
    TEMPEST,
    WHITE_NOISE,

    // Defect - rare
    ALL_FOR_ONE,
    BIASED_COGNITION,
    BUFFER,
    CORE_SURGE,
    CREATIVE_AI,
    ECHO_FORM,
    ELECTRODYNAMICS,
    FISSION,
    HYPERBEAM,
    MACHINE_LEARNING,
    METEOR_STRIKE,
    MULTI_CAST,
    RAINBOW,
    REBOOT,
    SEEK,
    THUNDER_STRIKE,

    // Colourless - uncommon
    BANDAGE_UP,
    BLIND,
    DARK_SHACKLES,
    DEEP_BREATH,
    DISCOVERY,
    DRAMATIC_ENTRANCE,
    ENLIGHTENMENT,
    FINESSE,
    FLASH_OF_STEEL,
    FORETHOUGHT,
    GOOD_INSTINCTS,
    IMPATIENCE,
    JACK_OF_ALL_TRADES,
    MADNESS,
    MIND_BLAST,
    PANACEA,
    PANIC_BUTTON,
    PURITY,
    SWIFT_STRIKE,
    TRIP,

    // Colourless - rare
    APOTHEOSIS,
    CHRYSALIS,
    HAND_OF_GREED,
    MAGNETISM,
    MASTER_OF_STRATEGY,
    MAYHEM,
    METAMORPHOSIS,
    PANACHE,
    SADISTIC_NATURE,
    SECRET_TECHNIQUE,
    SECRET_WEAPON,
    THE_BOMB,
    THINKING_AHEAD,
    TRANSMUTATION,
    VIOLENCE,

    // Colourless - handed out by relics and events
    BITE,
    RITUAL_DAGGER,
    JAX,
    INSIGHT,
    MIRACLE,
    SAFETY,

    APPARITION,

    // Status
    BURN,
    DAZED,
    SLIMED,
    VOID,
    WOUND,

    // Curse
    ASCENDERS_BANE,
    CLUMSY,
    CURSE_OF_THE_BELL,
    DECAY,
    DOUBT,
    INJURY,
    NECRONOMICURSE,
    NORMALITY,
    PAIN,
    PARASITE,
    PRIDE,
    REGRET,
    SHAME,
    WRITHE
};
}  // namespace ConquerTheSpire

#endif  // CONQUER_THE_SPIRE_CARD_ID_HPP
